apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: gambit
  namespace: gambit
spec:
  version: 7.13.3
  nodeSelector:
    gambit: worker     
  nodeSets:
  - name: store
    count: 1
    config:
      node.store.allow_mmap: false

