apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: gambit
  namespace: gambit
spec:
  version: 7.13.3
  count: 1
  elasticsearchRef:
    name: gambit
    namespace: gambit
  podTemplate:
    spec:
      nodeSelector:
        gambit: worker
